### ISSUE TITLE
无法解析url对应的歌单

### ISSUE THREAD

**Issue by littlemoji** [Bistutu/GoMusic#12]
<img width="1052" alt="image" src="https://github.com/Bistutu/GoMusic/assets/55924059/ac970c21-7fb4-4350-b73a-bb618e8d43ab">

**Comment by littlemoji** [comment]
![image](https://github.com/Bistutu/GoMusic/assets/55924059/f3d9d423-491d-4f06-bfff-31547a963373)
原来是没有权限🥲

**Comment by Bistutu** [comment]
🥲
