### ISSUE TITLE
网易云解析结果错误

### ISSUE THREAD

**Issue by littlemoji** [Bistutu/GoMusic#13]
实际歌单：https://music.163.com/album?id=35150843
解析结果：
<img width="579" alt="image" src="https://github.com/Bistutu/GoMusic/assets/55924059/a6d98c42-f3e5-4cda-aaa4-7a9d1e0954e3">

**Comment by Bistutu** [comment]
这是网易云专辑栏，目前还没有适配，期待后续

**Comment by 88lin** [comment]
qq音乐也是这样

**Comment by Bistutu** [comment]
> qq音乐也是这样

兄弟给个链接🥲我看看能不能修复

**Comment by 88lin** [comment]
https://y.qq.com/n/ryqq/playlist/1953563505

**Comment by Bistutu** [comment]
> https://y.qq.com/n/ryqq/playlist/1953563505

感谢提供，已修复！
