### ISSUE TITLE
https://music.unmeta.cn 无法打开，显示重定向次数过多

### ISSUE THREAD

**Issue by jingjiecb** [Bistutu/GoMusic#15]
打开[music.unmeta.cn](https://music.unmeta.cn/)后，显示重定向次数过多，网页无法加载。
![image](https://github.com/Bistutu/GoMusic/assets/47586961/3e39b8dc-9b39-4461-9318-ce5c9d931867)

**Comment by Bistutu** [comment]
感谢提醒，错误开启了cloudflare dns的一些功能，现已恢复
