### ISSUE TITLE
歌单太长会获取失败

### ISSUE THREAD

**Issue by AprilJoy** [Bistutu/GoMusic#18]
歌单太长的话就获取不到了，比如这个歌单https://c6.y.qq.com/base/fcgi-bin/u?__=IsJYxg8JsBRd

顺便推荐一下我自己的解决方案
https://mp.weixin.qq.com/s/sUzd35U-5FaEOYoSmAIE-g

**Comment by Bistutu** [comment]
感谢提供方案。

**Comment by N1na27mmk** [comment]
经过测试发现是因为网易云一次能传入的id有上限201，将neteasy.go中chunksize由500调整为200，可以分批次获取完整歌单，可以添加请求延迟避免出现意外。（我自己根据Gomusic方案编写了Obsidian的模版，改变参数后可以获得完整歌单列表，但没有本地部署gomusic项目并验证。）

**Comment by Bistutu** [comment]
> 经过测试发现是因为网易云一次能传入的id有上限201，将neteasy.go中chunksize由500调整为200，可以分批次获取完整歌单，可以添加请求延迟避免出现意外。（我自己根据Gomusic方案编写了Obsidian的模版，改变参数后可以获得完整歌单列表，但没有本地部署gomusic项目并验证。）

这个值我后面会调整下，调小点、每次获取的不要太多
