### ISSUE TITLE
关于这个项目

### ISSUE THREAD

**Issue by aptheparker** [Bistutu/GoMusic#7]
请问这个项目有最终目标吗？

目前来看功能感觉已经挺全，好奇作者构想的后续工程有哪些？

**Comment by Bistutu** [comment]
后续可能：
1、扩展其他平台，例如~~酷狗~~（尝试过，暂时放弃）、汽水音乐等
2、写另一个服务，定期去扫识别出来的歌单，看哪些歌曲在转入时会失败，这些歌曲在不同平台之间可能只是差了1-2个字，优化这种现象。
3、性能优化

**Comment by Bistutu** [comment]
没有最终目标

**Comment by aptheparker** [comment]
谢谢。
请问作者是否接受前端（VUE & EUI）的PR？

**Comment by Bistutu** [comment]
可以啊😝欢迎欢迎

**Comment by aptheparker** [comment]
请问作者有没有想法做一个open source？

**Comment by Bistutu** [comment]
现在不就是开源项目吗=？

**Comment by aptheparker** [comment]
> 现在不就是开源项目吗=？

啊 我应该问 ”有没有想法做另一个开源项目”的

**Comment by Elliot9527** [comment]
qq音乐-中文歌单获取空白，英文歌单可以获取

**Comment by Bistutu** [comment]
> qq音乐-中文歌单获取空白，英文歌单可以获取

可以提供一个链接吗🫠

**Comment by Elliot9527** [comment]
> > QQ音乐-中文歌单获取空白，中文歌单可以获取
> 
> 可以提供一个链接吗🫠



> > QQ音乐-中文歌单获取空白，中文歌单可以获取
> 
> 可以提供一个链接吗🫠

这个->https://y.qq.com/n/ryqq/playlist/7609607887

**Comment by Bistutu** [comment]
> > > QQ音乐-中文歌单获取空白，中文歌单可以获取
> > 
> > 
> > 可以提供一个链接吗🫠
> 
> > > QQ音乐-中文歌单获取空白，中文歌单可以获取
> > 
> > 
> > 可以提供一个链接吗🫠
> 
> 这个->https://y.qq.com/n/ryqq/playlist/7609607887

感谢提的bug，已修复，后台链接规则匹配问题
